export const product_data = {
  LC: {
    options: ["6EK", "6EJ", "6EN", "6EL", "6E2", "6E3"],
    dggRate: [80, 70, 90, 60, 75, 50],
    data: {
      "6EK": {
        monthly: [75, 85, 90, 78, 92, 88, 80, 95, 77, 84, 90, 91],
        weekly: [
          85, 87, 90, 92, 94, 77, 80, 82, 84, 86, 89, 91, 93, 95, 78, 81, 83,
          85, 87, 90, 92, 94, 77, 79, 82, 84, 86, 89, 91, 93, 95, 78, 80, 83,
          85, 87, 90, 92, 94, 77, 79, 82, 84, 86, 89, 91, 93, 95, 78, 80, 83,
          85, 87, 90, 92,
        ],
        before: {
          Total: 80,
          "C/C": 55,
          DIFF: 75,
          ETCH: 50,
          IMP: 65,
          PHOTO: 60,
          "T/F": 35,
        },
        present: {
          Total: 75,
          "C/C": 60,
          DIFF: 80,
          ETCH: 55,
          IMP: 70,
          PHOTO: 65,
          "T/F": 40,
        },
        before2: {
          Total: 70,
          IBG: 60,
          GT: 58,
          SAC: 62,
          SN: 59,
          MLM1: 61,
          MLM2: 57,
        },
        present2: {
          Total: 75,
          IBG: 65,
          GT: 63,
          SAC: 67,
          SN: 64,
          MLM1: 66,
          MLM2: 62,
        },
        dggRate: {
          IBG: 62,
          GT: 70,
          SAC: 78,
          SN: 65,
          MLM1: 60,
          MLM2: 68,
        },
        detail: "LC24GDS",
      },
      "6EJ": {
        monthly: [80, 88, 91, 76, 95, 85, 79, 92, 82, 89, 87, 90],
        weekly: [
          77, 79, 81, 83, 85, 88, 90, 92, 94, 96, 79, 81, 84, 86, 88, 90, 93,
          95, 77, 79, 81, 83, 85, 88, 90, 92, 94, 96, 79, 81, 84, 86, 88, 90,
          93, 95, 77, 79, 81, 83, 85, 88, 90, 92, 94, 96, 79, 81, 84, 86, 88,
          90, 93, 95,
        ],
        before: {
          Total: 70,
          "C/C": 55,
          DIFF: 75,
          ETCH: 50,
          IMP: 65,
          PHOTO: 60,
          "T/F": 35,
        },
        present: {
          Total: 75,
          "C/C": 60,
          DIFF: 80,
          ETCH: 55,
          IMP: 70,
          PHOTO: 65,
          "T/F": 40,
        },
        before2: {
          Total: 70,
          IBG: 60,
          GT: 58,
          SAC: 62,
          SN: 59,
          MLM1: 61,
          MLM2: 57,
        },
        present2: {
          Total: 75,
          IBG: 65,
          GT: 63,
          SAC: 67,
          SN: 64,
          MLM1: 66,
          MLM2: 62,
        },
        dggRate: {
          IBG: 68,
          GT: 72,
          SAC: 74,
          SN: 69,
          MLM1: 65,
          MLM2: 73,
        },
        detail: "LC16GDS",
      },
      "6EN": {
        monthly: [85, 78, 86, 80, 91, 84, 77, 94, 83, 86, 88, 89],
        weekly: [
          79, 81, 84, 86, 88, 90, 93, 95, 77, 79, 81, 83, 85, 88, 90, 92, 94,
          96, 79, 81, 84, 86, 88, 90, 93, 95, 77, 79, 81, 83, 85, 88, 90, 92,
          94, 96, 79, 81, 84, 86, 88, 90, 93, 95, 77, 79, 81, 83, 85, 88, 90,
          92, 94, 96,
        ],
        before: {
          Total: 70,
          "C/C": 55,
          DIFF: 75,
          ETCH: 50,
          IMP: 65,
          PHOTO: 60,
          "T/F": 35,
        },
        present: {
          Total: 75,
          "C/C": 60,
          DIFF: 80,
          ETCH: 55,
          IMP: 70,
          PHOTO: 65,
          "T/F": 40,
        },
        before2: {
          Total: 70,
          IBG: 60,
          GT: 58,
          SAC: 62,
          SN: 59,
          MLM1: 61,
          MLM2: 57,
        },
        present2: {
          Total: 75,
          IBG: 65,
          GT: 63,
          SAC: 67,
          SN: 64,
          MLM1: 66,
          MLM2: 62,
        },
        dggRate: {
          IBG: 72,
          GT: 67,
          SAC: 75,
          SN: 70,
          MLM1: 74,
          MLM2: 69,
        },
        detail: "LC32GDS",
      },
      "6EL": {
        monthly: [78, 92, 85, 83, 89, 87, 80, 93, 81, 84, 88, 90],
        weekly: [
          80, 82, 84, 87, 89, 91, 94, 96, 78, 80, 82, 84, 87, 89, 91, 94, 96,
          78, 80, 82, 84, 87, 89, 91, 94, 96, 78, 80, 82, 84, 87, 89, 91, 94,
          96, 78, 80, 82, 84, 87, 89, 91, 94, 96, 78, 80, 82, 84, 87, 89, 91,
          94, 96, 78,
        ],
        before: {
          Total: 70,
          "C/C": 55,
          DIFF: 75,
          ETCH: 50,
          IMP: 65,
          PHOTO: 60,
          "T/F": 35,
        },
        present: {
          Total: 75,
          "C/C": 60,
          DIFF: 80,
          ETCH: 55,
          IMP: 70,
          PHOTO: 65,
          "T/F": 40,
        },
        before2: {
          Total: 70,
          IBG: 60,
          GT: 58,
          SAC: 62,
          SN: 59,
          MLM1: 61,
          MLM2: 57,
        },
        present2: {
          Total: 75,
          IBG: 65,
          GT: 63,
          SAC: 67,
          SN: 64,
          MLM1: 66,
          MLM2: 62,
        },
        dggRate: {
          IBG: 64,
          GT: 71,
          SAC: 76,
          SN: 68,
          MLM1: 73,
          MLM2: 67,
        },
        detail: "LC16GLPDS",
      },
      "6E2": {
        monthly: [82, 85, 90, 93, 87, 80, 76, 92, 88, 89, 84, 90],
        weekly: [
          85, 87, 90, 92, 94, 77, 80, 82, 84, 86, 89, 91, 93, 95, 78, 81, 83,
          85, 87, 90, 92, 94, 77, 79, 82, 84, 86, 89, 91, 93, 95, 78, 80, 83,
          85, 87, 90, 92, 94, 77, 79, 82, 84, 86, 89, 91, 93, 95, 78, 80, 83,
          85, 87, 90, 92, 94, 77,
        ],
        before: {
          Total: 70,
          "C/C": 55,
          DIFF: 75,
          ETCH: 50,
          IMP: 65,
          PHOTO: 60,
          "T/F": 35,
        },
        present: {
          Total: 75,
          "C/C": 60,
          DIFF: 80,
          ETCH: 55,
          IMP: 70,
          PHOTO: 65,
          "T/F": 40,
        },
        before2: {
          Total: 70,
          IBG: 60,
          GT: 58,
          SAC: 62,
          SN: 59,
          MLM1: 61,
          MLM2: 57,
        },
        present2: {
          Total: 75,
          IBG: 65,
          GT: 63,
          SAC: 67,
          SN: 64,
          MLM1: 66,
          MLM2: 62,
        },
        dggRate: {
          IBG: 67,
          GT: 64,
          SAC: 69,
          SN: 71,
          MLM1: 62,
          MLM2: 75,
        },
        detail: "LC24GHBM3E Core",
      },
      "6E3": {
        monthly: [77, 80, 94, 85, 86, 83, 79, 91, 84, 87, 88, 90],
        weekly: [
          77, 79, 82, 84, 86, 89, 91, 93, 95, 78, 80, 83, 85, 87, 90, 92, 94,
          77, 79, 82, 84, 86, 89, 91, 93, 95, 78, 80, 83, 85, 87, 90, 92, 94,
          77, 79, 82, 84, 86, 89, 91, 93, 95, 78, 80, 83, 85, 87, 90, 92, 94,
          77, 79, 82, 84, 86, 89,
        ],
        before: {
          Total: 70,
          "C/C": 55,
          DIFF: 75,
          ETCH: 50,
          IMP: 65,
          PHOTO: 60,
          "T/F": 35,
        },
        present: {
          Total: 75,
          "C/C": 60,
          DIFF: 80,
          ETCH: 55,
          IMP: 70,
          PHOTO: 65,
          "T/F": 40,
        },
        before2: {
          Total: 70,
          IBG: 60,
          GT: 58,
          SAC: 62,
          SN: 59,
          MLM1: 61,
          MLM2: 57,
        },
        present2: {
          Total: 75,
          IBG: 65,
          GT: 63,
          SAC: 67,
          SN: 64,
          MLM1: 66,
          MLM2: 62,
        },
        dggRate: {
          IBG: 75,
          GT: 70,
          SAC: 72,
          SN: 67,
          MLM1: 73,
          MLM2: 68,
        },
        detail: "LC24GHBM3E Base",
      },
    },
  },
  CP: {
    options: ["4S4", "WAR"],
    dggRate: [80, 70],
    data: {
      "4S4": {
        monthly: [83, 76, 92, 80, 81, 90, 89, 88, 84, 85, 91, 87],
        weekly: [
          79, 81, 83, 86, 88, 90, 93, 95, 77, 79, 81, 83, 86, 88, 90, 93, 95,
          77, 79, 81, 83, 86, 88, 90, 93, 95, 77, 79, 81, 83, 86, 88, 90, 93,
          95, 77, 79, 81, 83, 86, 88, 90, 93, 95, 77, 79, 81, 83, 86, 88, 90,
          93, 95, 77,
        ],
        before: {
          Total: 70,
          "C/C": 55,
          DIFF: 75,
          ETCH: 50,
          IMP: 65,
          PHOTO: 60,
          "T/F": 35,
        },
        present: {
          Total: 75,
          "C/C": 60,
          DIFF: 80,
          ETCH: 55,
          IMP: 70,
          PHOTO: 65,
          "T/F": 40,
        },
        before2: {
          Total: 70,
          IBG: 60,
          GT: 58,
          SAC: 62,
          SN: 59,
          MLM1: 61,
          MLM2: 57,
        },
        present2: {
          Total: 75,
          IBG: 65,
          GT: 63,
          SAC: 67,
          SN: 64,
          MLM1: 66,
          MLM2: 62,
        },
        dggRate: {
          IBG: 60,
          GT: 73,
          SAC: 69,
          SN: 64,
          MLM1: 70,
          MLM2: 67,
        },
        detail: "CP8GDRN",
      },
      WAR: {
        monthly: [79, 88, 80, 85, 92, 83, 82, 91, 87, 86, 90, 84],
        weekly: [
          77, 79, 82, 84, 86, 89, 91, 93, 95, 78, 80, 83, 85, 87, 90, 92, 94,
          77, 79, 82, 84, 86, 89, 91, 93, 95, 78, 80, 83, 85, 87, 90, 92, 94,
          77, 79, 82, 84, 86, 89, 91, 93, 95, 78, 80, 83, 85, 87, 90, 92, 94,
          77, 79, 82, 84, 86, 89,
        ],
        before: {
          Total: 70,
          "C/C": 55,
          DIFF: 75,
          ETCH: 50,
          IMP: 65,
          PHOTO: 60,
          "T/F": 35,
        },
        present: {
          Total: 75,
          "C/C": 60,
          DIFF: 80,
          ETCH: 55,
          IMP: 70,
          PHOTO: 65,
          "T/F": 40,
        },
        before2: {
          Total: 70,
          IBG: 60,
          GT: 58,
          SAC: 62,
          SN: 59,
          MLM1: 61,
          MLM2: 57,
        },
        present2: {
          Total: 75,
          IBG: 65,
          GT: 63,
          SAC: 67,
          SN: 64,
          MLM1: 66,
          MLM2: 62,
        },
        dggRate: {
          IBG: 71,
          GT: 69,
          SAC: 72,
          SN: 67,
          MLM1: 65,
          MLM2: 74,
        },
        detail: "CP16GLPDSP",
      },
    },
  },
  RG: {
    options: ["WRD"],
    dggRate: [80],
    data: {
      WRD: {
        monthly: [92, 86, 80, 85, 89, 78, 84, 91, 90, 88, 87, 83],
        weekly: [
          79, 81, 84, 86, 88, 90, 93, 95, 77, 79, 81, 83, 86, 88, 90, 93, 95,
          77, 79, 81, 83, 86, 88, 90, 93, 95, 77, 79, 81, 83, 86, 88, 90, 93,
          95, 77, 79, 81, 83, 86, 88, 90, 93, 95, 77, 79, 81, 83, 86, 88, 90,
          93, 95, 77,
        ],
        before: {
          Total: 70,
          "C/C": 55,
          DIFF: 75,
          ETCH: 50,
          IMP: 65,
          PHOTO: 60,
          "T/F": 35,
        },
        present: {
          Total: 75,
          "C/C": 60,
          DIFF: 80,
          ETCH: 55,
          IMP: 70,
          PHOTO: 65,
          "T/F": 40,
        },
        before2: {
          Total: 70,
          IBG: 60,
          GT: 58,
          SAC: 62,
          SN: 59,
          MLM1: 61,
          MLM2: 57,
        },
        present2: {
          Total: 75,
          IBG: 65,
          GT: 63,
          SAC: 67,
          SN: 64,
          MLM1: 66,
          MLM2: 62,
        },
        dggRate: {
          IBG: 69,
          GT: 68,
          SAC: 71,
          SN: 67,
          MLM1: 64,
          MLM2: 70,
        },
        detail: "RG16GLPD4X",
      },
    },
  },
  SP: {
    options: ["4SA"],
    dggRate: [80],
    data: {
      "4SA": {
        monthly: [78, 92, 85, 80, 76, 89, 81, 90, 84, 83, 87, 88],
        weekly: [
          77, 79, 82, 84, 86, 89, 91, 93, 95, 78, 80, 83, 85, 87, 90, 92, 94,
          77, 79, 82, 84, 86, 89, 91, 93, 95, 78, 80, 83, 85, 87, 90, 92, 94,
          77, 79, 82, 84, 86, 89, 91, 93, 95, 78, 80, 83, 85, 87, 90, 92, 94,
          77, 79, 82, 84, 86, 89,
        ],
        before: {
          Total: 70,
          "C/C": 55,
          DIFF: 75,
          ETCH: 50,
          IMP: 65,
          PHOTO: 60,
          "T/F": 35,
        },
        present: {
          Total: 75,
          "C/C": 60,
          DIFF: 80,
          ETCH: 55,
          IMP: 70,
          PHOTO: 65,
          "T/F": 40,
        },
        before2: {
          Total: 70,
          IBG: 60,
          GT: 58,
          SAC: 62,
          SN: 59,
          MLM1: 61,
          MLM2: 57,
        },
        present2: {
          Total: 75,
          IBG: 65,
          GT: 63,
          SAC: 67,
          SN: 64,
          MLM1: 66,
          MLM2: 62,
        },
        dggRate: {
          IBG: 74,
          GT: 66,
          SAC: 72,
          SN: 64,
          MLM1: 67,
          MLM2: 69,
        },
        detail: "SP16GDS",
      },
    },
  },
};

export const TableDataAREA = [
  ["INDEX", "4월", "WW27", "C/C", "DIFF", "ETCH", "IMP", "PHOTO", "T/F"],
  [
    "Control Out",
    "9/385",
    "2/355",
    "0/23",
    "0/25",
    "2/151",
    "0/10",
    "0/131",
    "0/15",
  ],
  [
    "OCI Centering",
    "8/297",
    "6/267",
    "0/23",
    "1/25",
    "2/142",
    "0/10",
    "2/52",
    "1/15",
  ],
  [
    "Scatter",
    "3/385",
    "1/355",
    "0/23",
    "1/25",
    "1/151",
    "0/10",
    "0/131",
    "0/15",
  ],
  [
    "불량률",
    "16/385",
    "6/355",
    "0/23",
    "1/25",
    "2/151",
    "0/10",
    "2/131",
    "1/15",
  ],
  [
    "One PTS",
    "369/385",
    "349/355",
    "23/23",
    "24/25",
    "149/151",
    "10/10",
    "129/131",
    "14/15",
  ],
];

export const TableDataModule = [
  ["INDEX", "4월", "WW27", "IBG", "GT", "SAC", "SN", "MLM1", "MLM2"],
  [
    "Control Out",
    "9/385",
    "2/355",
    "9/385",
    "2/355",
    "0/23",
    "0/25",
    "2/151",
    "0/10",
  ],
  [
    "OCI Centering",
    "8/297",
    "6/267",
    "8/297",
    "6/267",
    "0/23",
    "1/25",
    "2/142",
    "0/10",
  ],
  [
    "Scatter",
    "3/385",
    "1/355",
    "3/385",
    "1/355",
    "0/23",
    "1/25",
    "1/151",
    "0/10",
  ],
  [
    "불량률",
    "16/385",
    "6/355",
    "16/385",
    "6/355",
    "0/23",
    "1/25",
    "2/151",
    "0/10",
  ],
  [
    "One PTS",
    "369/385",
    "349/355",
    "369/385",
    "349/355",
    "23/23",
    "24/25",
    "149/151",
    "10/10",
  ],
];

export const inspectionData = [
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q1",
    STEP: 1,
    STEP_DESC: "IS_E_C_C",
    DCOL_ITEM_CD: "edge_ex",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 1,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 2,
    STEP_DESC: "IS_E_C_C",
    DCOL_ITEM_CD: "edge_ex",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 1,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW24",
    제품명: "6EK",
    GRADE: "Q1",
    STEP: 3,
    STEP_DESC: "IS_E_C_C",
    DCOL_ITEM_CD: "edge_ex",
    Module: "IBG",
    AREA_ID: "DIFF",
    검출횟수: 1,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW25",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 4,
    STEP_DESC: "IS_E_C_C",
    DCOL_ITEM_CD: "edge_ex",
    Module: "IBG",
    AREA_ID: "DIFF",
    검출횟수: 1,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW26",
    제품명: "6EK",
    GRADE: "Q1",
    STEP: 5,
    STEP_DESC: "IS_E_C_C",
    DCOL_ITEM_CD: "edge_ex",
    Module: "IBG",
    AREA_ID: "T/F",
    검출횟수: 1,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW27",
    제품명: "6EK",
    GRADE: "Q1",
    STEP: 6,
    STEP_DESC: "IS_E_C_C",
    DCOL_ITEM_CD: "edge_ex",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 1,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW28",
    제품명: "6EK",
    GRADE: "Q1",
    STEP: 7,
    STEP_DESC: "IS_E_C_C",
    DCOL_ITEM_CD: "edge_ex",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 1,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW29",
    제품명: "6EK",
    GRADE: "Q1",
    STEP: 8,
    STEP_DESC: "IS_E_C_C",
    DCOL_ITEM_CD: "edge_ex",
    Module: "IBG",
    AREA_ID: "C/C",
    검출횟수: 1,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q1",
    STEP: 9,
    STEP_DESC: "IS_E_C_C",
    DCOL_ITEM_CD: "edge_ex",
    Module: "IBG",
    AREA_ID: "DIFF",
    검출횟수: 1,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EK",
    GRADE: "Q1",
    STEP: 10,
    STEP_DESC: "IS_E_C_C",
    DCOL_ITEM_CD: "edge_ex",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 1,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q1",
    STEP: 11,
    STEP_DESC: "IS_E_C_C",
    DCOL_ITEM_CD: "edge_ex",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 1,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EK",
    GRADE: "Q1",
    STEP: 12,
    STEP_DESC: "IS_E_C_C",
    DCOL_ITEM_CD: "edge_ex",
    Module: "IBG",
    AREA_ID: "C/C",
    검출횟수: 1,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q1",
    STEP: 13,
    STEP_DESC: "IS_E_C_C",
    DCOL_ITEM_CD: "edge_ex",
    Module: "IBG",
    AREA_ID: "T/F",
    검출횟수: 1,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EK",
    GRADE: "Q1",
    STEP: 14,
    STEP_DESC: "IS_E_C_OC",
    DCOL_ITEM_CD: "edge_ex",
    Module: "IBG",
    AREA_ID: "C/C",
    검출횟수: 1,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q1",
    STEP: 15,
    STEP_DESC: "IS_ H_O_D_T(R)",
    DCOL_ITEM_CD: "edge_ex",
    Module: "GT",
    AREA_ID: "IMP",
    검출횟수: 1,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q1",
    STEP: 16,
    STEP_DESC: "B_H_UT_D_P_T(R)",
    DCOL_ITEM_CD: "edge_ex",
    Module: "GT",
    AREA_ID: "ETCH",
    검출횟수: 1,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q1",
    STEP: 17,
    STEP_DESC: "B_P_M_C",
    DCOL_ITEM_CD: "edge_ex",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 3,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q1",
    STEP: 18,
    STEP_DESC: "B_P_M_C",
    DCOL_ITEM_CD: "edge_ex",
    Module: "SAC",
    AREA_ID: "DIFF",
    검출횟수: 3,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q1",
    STEP: 19,
    STEP_DESC: "B_P_E_C",
    DCOL_ITEM_CD: "edge_ex",
    Module: "IBG",
    AREA_ID: "T/F",
    검출횟수: 3,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q1",
    STEP: 20,
    STEP_DESC: "B_P_E_C",
    DCOL_ITEM_CD: "edge_ex",
    Module: "SN",
    AREA_ID: "DIFF",
    검출횟수: 3,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q1",
    STEP: 21,
    STEP_DESC: "B_E_C_C",
    DCOL_ITEM_CD: "edge_ex",
    Module: "SN",
    AREA_ID: "PHOTO",
    검출횟수: 3,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q1",
    STEP: 22,
    STEP_DESC: "B_E_C_C",
    DCOL_ITEM_CD: "edge_ex",
    Module: "SN",
    AREA_ID: "DIFF",
    검출횟수: 3,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q1",
    STEP: 23,
    STEP_DESC: "B_E_C_C",
    DCOL_ITEM_CD: "edge_ex",
    Module: "SN",
    AREA_ID: "PHOTO",
    검출횟수: 3,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q1",
    STEP: 24,
    STEP_DESC: "B_E_C_C",
    DCOL_ITEM_CD: "edge_ex",
    Module: "SN",
    AREA_ID: "PHOTO",
    검출횟수: 3,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q1",
    STEP: 25,
    STEP_DESC: "B_E_C_OC",
    DCOL_ITEM_CD: "edge_ex",
    Module: "SN",
    AREA_ID: "ETCH",
    검출횟수: 3,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EN",
    GRADE: "Q1",
    STEP: 26,
    STEP_DESC: "B_E_C_OC",
    DCOL_ITEM_CD: "edge_ex",
    Module: "SN",
    AREA_ID: "ETCH",
    검출횟수: 3,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EN",
    GRADE: "Q1",
    STEP: 27,
    STEP_DESC: "B_E_C_OC",
    DCOL_ITEM_CD: "edge_ex",
    Module: "SN",
    AREA_ID: "DIFF",
    검출횟수: 3,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EN",
    GRADE: "Q1",
    STEP: 28,
    STEP_DESC: "B_E_C_OC",
    DCOL_ITEM_CD: "edge_ex",
    Module: "SN",
    AREA_ID: "C/C",
    검출횟수: 3,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EN",
    GRADE: "Q1",
    STEP: 29,
    STEP_DESC: "B_E_C_OC",
    DCOL_ITEM_CD: "edge_ex",
    Module: "SN",
    AREA_ID: "C/C",
    검출횟수: 3,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EN",
    GRADE: "Q1",
    STEP: 30,
    STEP_DESC: "B_OX_T(R)",
    DCOL_ITEM_CD: "edge_ex",
    Module: "SN",
    AREA_ID: "C/C",
    검출횟수: 3,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EN",
    GRADE: "Q1",
    STEP: 31,
    STEP_DESC: "B_OX_T(R)",
    DCOL_ITEM_CD: "edge_ex",
    Module: "SN",
    AREA_ID: "C/C",
    검출횟수: 3,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EN",
    GRADE: "Q1",
    STEP: 32,
    STEP_DESC: "B_M_EB_C_OC",
    DCOL_ITEM_CD: "edge_ex",
    Module: "SN",
    AREA_ID: "ETCH",
    검출횟수: 3,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EN",
    GRADE: "Q1",
    STEP: 33,
    STEP_DESC: "B_M_EB_C_OC",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SN",
    AREA_ID: "ETCH",
    검출횟수: 3,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EN",
    GRADE: "Q1",
    STEP: 34,
    STEP_DESC: "B_M_EB_C_OC",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SN",
    AREA_ID: "ETCH",
    검출횟수: 3,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EN",
    GRADE: "Q1",
    STEP: 35,
    STEP_DESC: "B_S_N_C_P_T(R)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM1",
    AREA_ID: "ETCH",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EN",
    GRADE: "Q1",
    STEP: 36,
    STEP_DESC: "B_S_N_C_P_T(R)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM1",
    AREA_ID: "ETCH",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EN",
    GRADE: "Q0",
    STEP: 37,
    STEP_DESC: "B_P_D_T(R)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "GT",
    AREA_ID: "ETCH",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 38,
    STEP_DESC: "B_P_EB_C_OC",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 39,
    STEP_DESC: "G_IL_O_T(R)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SN",
    AREA_ID: "PHOTO",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW24",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 40,
    STEP_DESC: "G_IL_O_T(R)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SN",
    AREA_ID: "PHOTO",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW24",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 41,
    STEP_DESC: "G_H_N_C_P_T(R)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM1",
    AREA_ID: "PHOTO",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW24",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 42,
    STEP_DESC: "G_H_N_C_P_T(R)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM1",
    AREA_ID: "PHOTO",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 43,
    STEP_DESC: "G_M_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "PHOTO",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 44,
    STEP_DESC: "G_M_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "PHOTO",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 45,
    STEP_DESC: "G_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 46,
    STEP_DESC: "G_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 47,
    STEP_DESC: "I_H_P_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6E2",
    GRADE: "Q0",
    STEP: 48,
    STEP_DESC: "I_H_P_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6E2",
    GRADE: "Q0",
    STEP: 49,
    STEP_DESC: "B_P_P_D_T(R)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "GT",
    AREA_ID: "PHOTO",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6E2",
    GRADE: "Q0",
    STEP: 50,
    STEP_DESC: "G_S_O_E_P_T(R)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6E2",
    GRADE: "Q0",
    STEP: 51,
    STEP_DESC: "G_S_O_E_P_T(R)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6E2",
    GRADE: "Q0",
    STEP: 52,
    STEP_DESC: "BL_H_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6E2",
    GRADE: "Q0",
    STEP: 53,
    STEP_DESC: "BL_H_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6E2",
    GRADE: "Q0",
    STEP: 54,
    STEP_DESC: "BL_M_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW24",
    제품명: "6E2",
    GRADE: "Q0",
    STEP: 55,
    STEP_DESC: "BL_M_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW24",
    제품명: "6E2",
    GRADE: "Q0",
    STEP: 56,
    STEP_DESC: "BL_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6E3",
    GRADE: "Q0",
    STEP: 57,
    STEP_DESC: "BL_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6E3",
    GRADE: "Q0",
    STEP: 58,
    STEP_DESC: "BL_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW24",
    제품명: "6E3",
    GRADE: "Q0",
    STEP: 59,
    STEP_DESC: "BL_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 4,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6E3",
    GRADE: "Q0",
    STEP: 60,
    STEP_DESC: "BL_E_C_OC",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "C/C",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6E3",
    GRADE: "Q0",
    STEP: 61,
    STEP_DESC: "BL_E_C_OC",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "C/C",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6E3",
    GRADE: "Q0",
    STEP: 62,
    STEP_DESC: "BL_E_C_C_P(C)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "DIFF",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6E3",
    GRADE: "Q0",
    STEP: 63,
    STEP_DESC: "BL_E_C_C_P(C)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "DIFF",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 64,
    STEP_DESC: "BL_E_C_C_P(C)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "DIFF",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 65,
    STEP_DESC: "BL_E_C_C_P(C)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "DIFF",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 66,
    STEP_DESC: "BL_E_C_C_P(C)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "PHOTO",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 67,
    STEP_DESC: "BL_E_C_C_P(C)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "PHOTO",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 68,
    STEP_DESC: "BL_E_C_C_P(C)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "PHOTO",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 69,
    STEP_DESC: "BL_E_C_C_P(C)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "PHOTO",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 70,
    STEP_DESC: "BL_E_C_C_P(C)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "PHOTO",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 71,
    STEP_DESC: "BL_E_C_C_P(C)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "PHOTO",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 72,
    STEP_DESC: "BL_E_C_C_P(C)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW25",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 73,
    STEP_DESC: "BL_E_C_C_P(C)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW25",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 74,
    STEP_DESC: "BL_E_C_C_P(C)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "T/F",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW25",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 75,
    STEP_DESC: "BL_E_C_C_P(C)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "DIFF",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 76,
    STEP_DESC: "BL_E_C_C_P(C)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "DIFF",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 77,
    STEP_DESC: "BL_E_C_C_P(C)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 78,
    STEP_DESC: "GB(C)_P_E_T(R)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "WAR",
    GRADE: "Q0",
    STEP: 79,
    STEP_DESC: "CB_H_N_D_P_T(R)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "GT",
    AREA_ID: "ETCH",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "WAR",
    GRADE: "Q0",
    STEP: 80,
    STEP_DESC: "CB_S_O_D_P_T(R)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "GT",
    AREA_ID: "ETCH",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "WAR",
    GRADE: "Q0",
    STEP: 81,
    STEP_DESC: "CB_H_N_C_P_T(R)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM1",
    AREA_ID: "ETCH",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "WAR",
    GRADE: "Q0",
    STEP: 82,
    STEP_DESC: "CB_H_N_C_P_T(R)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM1",
    AREA_ID: "ETCH",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "WAR",
    GRADE: "Q0",
    STEP: 83,
    STEP_DESC: "CB_H_E_ C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM2",
    AREA_ID: "ETCH",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "WAR",
    GRADE: "Q0",
    STEP: 84,
    STEP_DESC: "CB_H_E_ C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM2",
    AREA_ID: "ETCH",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "WAR",
    GRADE: "Q0",
    STEP: 85,
    STEP_DESC: "CB_E2_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM2",
    AREA_ID: "ETCH",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "WAR",
    GRADE: "Q0",
    STEP: 86,
    STEP_DESC: "CB_E2_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM2",
    AREA_ID: "ETCH",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "WAR",
    GRADE: "Q0",
    STEP: 87,
    STEP_DESC: "CB_E2_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM2",
    AREA_ID: "IMP",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "WAR",
    GRADE: "Q0",
    STEP: 88,
    STEP_DESC: "CB_E2_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM2",
    AREA_ID: "IMP",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "WAR",
    GRADE: "Q0",
    STEP: 89,
    STEP_DESC: "CB_E2_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM2",
    AREA_ID: "IMP",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "W7D",
    GRADE: "Q0",
    STEP: 90,
    STEP_DESC: "CB_E2_C_OC",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM2",
    AREA_ID: "IMP",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "W7D",
    GRADE: "Q0",
    STEP: 91,
    STEP_DESC: "CB_E2_C_OC",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM2",
    AREA_ID: "PHOTO",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "W7D",
    GRADE: "Q0",
    STEP: 92,
    STEP_DESC: "CB_E2_C_OC",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM2",
    AREA_ID: "PHOTO",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW24",
    제품명: "W7D",
    GRADE: "Q0",
    STEP: 93,
    STEP_DESC: "CB_E2_C_OC",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM2",
    AREA_ID: "T/F",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW24",
    제품명: "W7D",
    GRADE: "Q0",
    STEP: 94,
    STEP_DESC: "CB_S_S_D_P_T(R)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM2",
    AREA_ID: "C/C",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW24",
    제품명: "W7D",
    GRADE: "Q0",
    STEP: 95,
    STEP_DESC: "I1(P)_S_C_P_T(R)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM1",
    AREA_ID: "ETCH",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW24",
    제품명: "W7D",
    GRADE: "Q0",
    STEP: 96,
    STEP_DESC: "I1(P)_S_C_P_T(R)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM1",
    AREA_ID: "ETCH",
    검출횟수: 6,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "W7D",
    GRADE: "Q0",
    STEP: 97,
    STEP_DESC: "I3_A_T_C_P_T(R)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM1",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "W7D",
    GRADE: "Q0",
    STEP: 98,
    STEP_DESC: "I3_A_T_C_P_T(R)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM1",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "W7D",
    GRADE: "Q0",
    STEP: 99,
    STEP_DESC: "IS(P)_+_C_M_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "W7D",
    GRADE: "Q0",
    STEP: 100,
    STEP_DESC: "IS(P)_+_C_M_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "W7D",
    GRADE: "Q0",
    STEP: 101,
    STEP_DESC: "IS_S_C_P_T(R)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM1",
    AREA_ID: "C/C",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "W7D",
    GRADE: "Q0",
    STEP: 102,
    STEP_DESC: "IS_S_C_P_T(R)",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "MLM1",
    AREA_ID: "C/C",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "W7D",
    GRADE: "Q0",
    STEP: 103,
    STEP_DESC: "IS_L_P_D_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "GT",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "W7D",
    GRADE: "Q0",
    STEP: 104,
    STEP_DESC: "IS_L_P_D_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "GT",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "W7D",
    GRADE: "Q0",
    STEP: 105,
    STEP_DESC: "IS_P_S_O_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "T/F",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "W7D",
    GRADE: "Q0",
    STEP: 106,
    STEP_DESC: "IS_P_S_O_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "T/F",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "W7D",
    GRADE: "Q0",
    STEP: 107,
    STEP_DESC: "IS_P_S_O_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "DIFF",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 108,
    STEP_DESC: "IS_P_S_O_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "IMP",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 109,
    STEP_DESC: "IS_P_S_O_D_C2",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "GT",
    AREA_ID: "IMP",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 110,
    STEP_DESC: "IS_P_S_O_D_C2",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "GT",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 111,
    STEP_DESC: "M0_M_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 112,
    STEP_DESC: "M0_M_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 113,
    STEP_DESC: "M0_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 114,
    STEP_DESC: "M0_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 115,
    STEP_DESC: "S2_+_M0_M_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 116,
    STEP_DESC: "S2_+_M0_M_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 117,
    STEP_DESC: "S2_+_M0_W_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 118,
    STEP_DESC: "S2_+_M0_W_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 119,
    STEP_DESC: "S2_+_M0_W_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 120,
    STEP_DESC: "S2_+_M0_W_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "4AS",
    GRADE: "Q0",
    STEP: 121,
    STEP_DESC: "S2_+_M0_W_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 122,
    STEP_DESC: "S2_+_M0_W_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW24",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 123,
    STEP_DESC: "S2_+_M0_H_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "DIFF",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW24",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 124,
    STEP_DESC: "S2_+_M0_H_E_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW24",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 125,
    STEP_DESC: "SC_P_M_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW24",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 126,
    STEP_DESC: "SC_P_M_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW24",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 127,
    STEP_DESC: "SC_P_S_O_D_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "GT",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW24",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 128,
    STEP_DESC: "SC_P_S_O_D_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "GT",
    AREA_ID: "DIFF",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 129,
    STEP_DESC: "SC_E_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SN",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 130,
    STEP_DESC: "SC_E_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 131,
    STEP_DESC: "SC_S_E_C_OC",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SN",
    AREA_ID: "DIFF",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 132,
    STEP_DESC: "S_H_EB_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SN",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 133,
    STEP_DESC: "S_H_EB_C_C",
    DCOL_ITEM_CD: "edge_e_avg",
    Module: "SN",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW24",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 134,
    STEP_DESC: "S_H_EB_C_C",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "SN",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW25",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 135,
    STEP_DESC: "S_H_EB_C_C",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "SN",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW26",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 136,
    STEP_DESC: "S_H_EB_C_OC",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW27",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 137,
    STEP_DESC: "S_H_EB_C_OC",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "IBG",
    AREA_ID: "C/C",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 138,
    STEP_DESC: "S_H_EB_C_OC",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "IBG",
    AREA_ID: "DIFF",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 139,
    STEP_DESC: "S_H_EB_C_OC",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "IBG",
    AREA_ID: "C/C",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 140,
    STEP_DESC: "S_H_EB_C_OC",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "IBG",
    AREA_ID: "C/C",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EL",
    GRADE: "Q0",
    STEP: 141,
    STEP_DESC: "S_H_EB_C_OC",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "IBG",
    AREA_ID: "IMP",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 142,
    STEP_DESC: "S_H_EB_C_OC",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 143,
    STEP_DESC: "S_B_C_P_T(R)",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "MLM1",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 144,
    STEP_DESC: "S_B_C_P_T(R)",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "MLM1",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 145,
    STEP_DESC: "S2(C)_G_O_D_P_T(R)",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "GT",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 146,
    STEP_DESC: "S_H_P_E_C_OC",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 147,
    STEP_DESC: "S_H_P_E_C_OC",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 148,
    STEP_DESC: "S_H_P_E_C_OC",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 149,
    STEP_DESC: "S_H_P_E_C_OC",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 150,
    STEP_DESC: "S_H_P_E_C_OC",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 151,
    STEP_DESC: "S_H_P_E_C_OC",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 152,
    STEP_DESC: "S_H_P_E_C_OC",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 153,
    STEP_DESC: "S_H_O_E_C_C",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 154,
    STEP_DESC: "S_H_O_E_C_C",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 155,
    STEP_DESC: "S_H_O_E_C_C",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 156,
    STEP_DESC: "S_H_O_E_C_C",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 157,
    STEP_DESC: "S_H_O_E_C_OC",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "MLM1",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 158,
    STEP_DESC: "S_H_O_E_C_OC",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "MLM1",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 159,
    STEP_DESC: "S_H_O_E_P_S_OC",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 160,
    STEP_DESC: "S_H_O_E_P_S_OC",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 161,
    STEP_DESC: "S_O_E_C_OC",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 162,
    STEP_DESC: "S_N_E_C_C",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 163,
    STEP_DESC: "S_N_E_C_C",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 164,
    STEP_DESC: "PL(P)_M_C",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 165,
    STEP_DESC: "PL(P)_M_C",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "SAC",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 166,
    STEP_DESC: "PL(P)_E_C_C_H",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "SAC",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EK",
    GRADE: "Q0",
    STEP: 167,
    STEP_DESC: "PL(P)_E_C_C_H",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "SAC",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 168,
    STEP_DESC: "PL(P)_E_C_C_H",
    DCOL_ITEM_CD: "WAFER_AVG",
    Module: "SAC",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 169,
    STEP_DESC: "PL(P)_E_C_C_H",
    DCOL_ITEM_CD: "WAFER_%^%_2",
    Module: "SAC",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 170,
    STEP_DESC: "MC_M_C",
    DCOL_ITEM_CD: "WAFER_%^%_3",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 171,
    STEP_DESC: "MC_M_C",
    DCOL_ITEM_CD: "WAFER_%^%_4",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 172,
    STEP_DESC: "MC_E_C",
    DCOL_ITEM_CD: "WAFER_%^%_5",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 173,
    STEP_DESC: "MC_E_C",
    DCOL_ITEM_CD: "WAFER_%^%_6",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 174,
    STEP_DESC: "MC_E_C",
    DCOL_ITEM_CD: "WAFER_%^%_7",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 175,
    STEP_DESC: "MC_E_C",
    DCOL_ITEM_CD: "WAFER_%^%_8",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 176,
    STEP_DESC: "MC_E_C",
    DCOL_ITEM_CD: "WAFER_%^%_9",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 177,
    STEP_DESC: "MC_E_C",
    DCOL_ITEM_CD: "WAFER_%^%_10",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 178,
    STEP_DESC: "MC_W_C_P_T(R)",
    DCOL_ITEM_CD: "WAFER_%^%_11",
    Module: "MLM1",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 179,
    STEP_DESC: "M_M_C",
    DCOL_ITEM_CD: "WAFER_%^%_12",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 180,
    STEP_DESC: "M_M_C",
    DCOL_ITEM_CD: "WAFER_%^%_13",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 181,
    STEP_DESC: "M_E_C_C",
    DCOL_ITEM_CD: "WAFER_%^%_14",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 182,
    STEP_DESC: "M_E_C_C",
    DCOL_ITEM_CD: "WAFER_%^%_15",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 183,
    STEP_DESC: "MC2_M_C",
    DCOL_ITEM_CD: "WAFER_%^%_16",
    Module: "SAC",
    AREA_ID: "PHOTO",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 184,
    STEP_DESC: "MC2_M_C",
    DCOL_ITEM_CD: "WAFER_%^%_17",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 185,
    STEP_DESC: "MC2_E_C_C",
    DCOL_ITEM_CD: "WAFER_%^%_18",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 186,
    STEP_DESC: "MC2_E_C_C",
    DCOL_ITEM_CD: "WAFER_%^%_19",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 2,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 187,
    STEP_DESC: "M2_M_C",
    DCOL_ITEM_CD: "WAFER_%^%_20",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 8,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 188,
    STEP_DESC: "M2_M_C",
    DCOL_ITEM_CD: "WAFER_%^%_21",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 8,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 189,
    STEP_DESC: "M2_E_C_C",
    DCOL_ITEM_CD: "WAFER_%^%_22",
    Module: "IBG",
    AREA_ID: "C/C",
    검출횟수: 8,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 190,
    STEP_DESC: "M2_E_C_C",
    DCOL_ITEM_CD: "WAFER_%^%_23",
    Module: "IBG",
    AREA_ID: "C/C",
    검출횟수: 8,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 191,
    STEP_DESC: "MC3_M_C",
    DCOL_ITEM_CD: "WAFER_%^%_24",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 8,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 192,
    STEP_DESC: "MC3_M_C",
    DCOL_ITEM_CD: "WAFER_%^%_25",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 8,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 193,
    STEP_DESC: "MC3_E_C_C",
    DCOL_ITEM_CD: "WAFER_%^%_26",
    Module: "IBG",
    AREA_ID: "T/F",
    검출횟수: 8,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 194,
    STEP_DESC: "MC3_E_C_C",
    DCOL_ITEM_CD: "WAFER_%^%_27",
    Module: "IBG",
    AREA_ID: "ETCH",
    검출횟수: 8,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 195,
    STEP_DESC: "M3_M_C",
    DCOL_ITEM_CD: "WAFER_%^%_28",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 8,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 196,
    STEP_DESC: "M3_M_C",
    DCOL_ITEM_CD: "WAFER_%^%_29",
    Module: "SAC",
    AREA_ID: "T/F",
    검출횟수: 8,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 197,
    STEP_DESC: "M3_E_C_C",
    DCOL_ITEM_CD: "WAFER_%^%_30",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 8,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 198,
    STEP_DESC: "M3_E_C_C",
    DCOL_ITEM_CD: "WAFER_%^%_31",
    Module: "IBG",
    AREA_ID: "PHOTO",
    검출횟수: 8,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EJ",
    GRADE: "Q0",
    STEP: 199,
    STEP_DESC: "S2_+_M_W_E_C_C_A(C)",
    DCOL_ITEM_CD: "WAFER_%^%_32",
    Module: "SAC",
    AREA_ID: "PHOTO",
    검출횟수: 8,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EN",
    GRADE: "Q0",
    STEP: 200,
    STEP_DESC: "S2_+_M_W_E_C_C_A(C)",
    DCOL_ITEM_CD: "WAFER_%^%_33",
    Module: "SAC",
    AREA_ID: "PHOTO",
    검출횟수: 8,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EN",
    GRADE: "Q0",
    STEP: 201,
    STEP_DESC: "S2_+_M_W_E_C_C_A(C)",
    DCOL_ITEM_CD: "WAFER_%^%_34",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 8,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EN",
    GRADE: "Q0",
    STEP: 202,
    STEP_DESC: "S2_+_M_W_E_C_C_A(C)",
    DCOL_ITEM_CD: "WAFER_%^%_35",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 8,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EN",
    GRADE: "Q0",
    STEP: 203,
    STEP_DESC: "S2_+_M_W_E_C_C_A(C)",
    DCOL_ITEM_CD: "T2_AVG",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 8,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EN",
    GRADE: "Q0",
    STEP: 204,
    STEP_DESC: "S2_+_M_W_E_C_C_A(C)",
    DCOL_ITEM_CD: "T3_AVG",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 8,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW23",
    제품명: "6EN",
    GRADE: "Q0",
    STEP: 205,
    STEP_DESC: "S2_+_M_W_E_C_C_A(C)",
    DCOL_ITEM_CD: "T4_AVG",
    Module: "SAC",
    AREA_ID: "ETCH",
    검출횟수: 8,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EN",
    GRADE: "Q0",
    STEP: 206,
    STEP_DESC: "S2_+_M_W_E_C_C_A(C)",
    DCOL_ITEM_CD: "T5_AVG",
    Module: "SAC",
    AREA_ID: "PHOTO",
    검출횟수: 8,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
  {
    주차: "WW22",
    제품명: "6EN",
    GRADE: "Q0",
    STEP: 207,
    STEP_DESC: "T_P_W_C_P_T(R)",
    DCOL_ITEM_CD: "T6_AVG",
    Module: "MLM1",
    AREA_ID: "ETCH",
    검출횟수: 8,
    IM: {
      num: 1234567,
      comment: "안녕하세요",
    },
    PI: {
      num: 1234567,
      comment: "안녕하세요",
    },
    공정: {
      num: 1234567,
      comment: "안녕하세요",
    },
  },
];
